name: Rollback to Tag - Manual

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag version to rollback to'
        required: true
        type: string
        default: ''
      workflow_branch:
        description: 'Branch to run the workflow on'
        required: true
        type: string
        default: 'infra-v2-dev'

jobs:
  trigger-pre-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pre-release Workflow
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{ secrets.PAT_TOKEN }}
          workflow-org: 'Riskidev'
          workflow-repo: 'Infra-v2'
          workflow-yaml: 'rollback-app-to-tag.yml'
          workflow-branch: '${{ inputs.workflow_branch }}'
          workflow-inputs: '{\"tag_name\": \"${{ inputs.tag_name }}\", \"repo_url\": \"${{ github.repository }}\", \"workflow_branch\": \"${{ inputs.workflow_branch }}\"}'