name: Rollback to Tag - Manual

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag version to rollback to'
        required: true
        type: string
        default: ''

jobs:
  trigger-pre-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pre-release Workflow
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{ secrets.PAT_TOKEN }}
          workflow-org: 'Riskidev'
          workflow-repo: 'Infra-v2'
          workflow-yaml: 'build-app-on-pre-release.yml'
          workflow-branch: 'infra-v2-dev'
          workflow-inputs: '{\"tag_name\": \"${{ inputs.tag_name }}\", \"repo_url\": \"${{ github.repository }}\"}'