name: Thunderstore UI - Pre-release

on:
  release:
    types: [prereleased]
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pre-release Workflow
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run build-thunderstore-ui-pre-release.yml \
          --repo Riskidev/Infra-v2 \
          --ref infra-v2-qa \
          -f tag_name=${{ github.event.release.tag_name }} \
          -f repo_url=${{ github.repository }}

