name: Thunderstore UI - Releasedd

on:
  release:
    types: [released]
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh workflow run build-thunderstore-ui-release.yml \
          --repo Riskidev/Infra-v2 \
          --ref infra-v2-prod \
          -f tag_name=${{ github.event.release.tag_name }} \
          -f repo_url=${{ github.repository }}

