name: Thunderstore UI Release

on:
  release:
    types: [released]
jobs:
  trigger-pre-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{ secrets.PAT_TOKEN }}
          workflow-org: 'Riskidev'
          workflow-repo: 'Infra-v2'
          workflow-yaml: 'build-thunderstore-ui-release.yml'
          workflow-branch: 'infra-v2-prod'
          workflow-inputs: '{\"tag_name\": \"${{ github.event.release.tag_name }}\", \"repo_url\": \"${{ github.repository }}\"}'
          wait-timeout-in-minutes: 15
