name: Trigger on Release

on:
  release:
    types: [released]

jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Release Workflow
        run: echo "Trigger Release Workflow"