name: Trigger on Pre-release

on:
  release:
    types: [published,prereleased,edited]
jobs:
  trigger-pre-release-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pre-release Workflow
        run: echo "Trigger Pre-release Workflow"