name: Trigger on Release

on:
  release:
    types: [published,released,edited]
jobs:
  trigger-release-workflow:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - name: Trigger Release Workflow
        run: echo "Trigger Release Workflow"