name: Handle Tag Creation

on:
  push:
    tags:
      - '*'
  
jobs:
  trigger-remote-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Workflow
        uses: anecdotes-ai/remote-workflow-control@latest
        with:
          github-auth-token: ${{ secrets.PAT_TOKEN }}
          workflow-org: 'Riskidev'
          workflow-repo: 'Infra-v2'
          workflow-yaml: 'receive_tag_update.yml'
          workflow-branch: 'infra-v2-dev'
          workflow-inputs: '{\"tag_name\": \"${{ github.ref_name }}\"}'